name: ShellCheck

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    name: ShellCheck Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: '.'
        format: gcc
        severity: warning
        additional_files: |
          docker_backup.sh
          test_rsync_fix.sh
      
    - name: Upload ShellCheck results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: shellcheck-results
        path: shellcheck-results.txt